package Exceptions;

public class ExceptionsNotes
{
	public static void main(String[] args)
	{
//	.	Java Try-Catch Block
//	.	Java Multiple Catch Block
//	.	Java Nested Try
//	.	Java Finally Block
//	.	Java Throw Keyword
//	.	Java Exception Propagation
//	.	Java Throws Keyword
//	.	Java Throw vs Throws
//	.	Java Final vs Finally vs Finalize
//	.	Java Exception Handling with Method Overriding
//	.	Java Custom Exceptions
		
		
		//1.one try with multiple catch block:
		
//		At a time only one exception occurs and at a time only one catch block is executed.
//		All catch blocks must be ordered from most specific to most general, 
//		i.e. catch for ArithmeticException must come before catch for Exception.
		
//		try{    
//            int a[]=new int[5];    
//            a[5]=30/0;    
//           }    
//           catch(ArithmeticException e)  
//              {  
//               System.out.println("Arithmetic Exception occurs");  
//              }    
//           catch(ArrayIndexOutOfBoundsException e)  
//              {  
//               System.out.println("ArrayIndexOutOfBounds Exception occurs");  
//              }    
//           catch(Exception e)  
//              {  
//               System.out.println("Parent Exception occurs");  
//              }  
		
//	2.Nested Try bock:java t point
		
//3.Finally :It is a block used to execute important code such as closing the connection, etc.
//		.Java finally block is always executed whether an exception is handled or not.
//		Therefore, it contains all the necessary statements that need to be printed regardless 
//		of the exception occurs or not.
		
			
//	4.Throw  Kerword: java t point
		
//	5.Throws keyword:
		
//		6.Difference sbetween Throw and Throws
		
		
		
		
	}

}
